# CodeRabbit Configuration for Quantum Kuiper
# AI Voice Agent Platform - Production-Grade Review Settings

language: en-US
early_access: false

reviews:
  profile: assertive  # Thorough reviews for production code
  request_changes_workflow: true
  high_level_summary: true
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "DRAFT"
    drafts: false
    base_branches:
      - master
      - main

  # Review output settings
  poem: false
  review_status: true
  collapse_walkthrough: false
  sequence_diagrams: true
  changed_files_summary: true

  # Path-specific review instructions
  path_instructions:
    - path: "src/app/api/**/*.ts"
      instructions: |
        API Route Security Checklist:
        - âœ… Input validation using Zod schemas from src/lib/validation.ts
        - âœ… SSRF protection (no localhost/private IPs in URLs)
        - âœ… SQL injection prevention (use parameterized queries)
        - âœ… Error handling with proper HTTP status codes
        - âœ… Rate limiting considerations
        - âœ… Authentication/authorization checks
        - âœ… Logging with winston (no sensitive data in logs)

    - path: "backend/**/*.js"
      instructions: |
        Backend/WebSocket Security:
        - âœ… WebSocket authentication
        - âœ… Message validation
        - âœ… Error handling
        - âœ… Resource cleanup (close connections)
        - âœ… Rate limiting for voice streams

    - path: "src/lib/**/*.ts"
      instructions: |
        Library Code Standards:
        - âœ… TypeScript strict mode compliance
        - âœ… Proper error handling
        - âœ… Performance optimization (avoid O(nÂ²) operations)
        - âœ… Security best practices
        - âœ… JSDoc comments for public APIs
        - âœ… Unit test coverage

    - path: "tests/**/*.test.ts"
      instructions: |
        Test Quality Checks:
        - âœ… Test coverage >70%
        - âœ… Edge cases covered
        - âœ… Error conditions tested
        - âœ… Mocks used appropriately
        - âœ… Assertions are clear and specific
        - âœ… No flaky tests

    - path: "**/*.sql"
      instructions: |
        SQL Security & Performance:
        - âœ… No SQL injection vulnerabilities
        - âœ… Proper indexes for queries
        - âœ… Row Level Security (RLS) policies
        - âœ… Performance with 100K+ rows
        - âœ… Foreign key constraints
        - âœ… NOT NULL constraints where appropriate

    - path: "src/middleware.ts"
      instructions: |
        Security Headers Review:
        - âœ… CSP (Content Security Policy)
        - âœ… CORS configuration
        - âœ… HSTS in production
        - âœ… X-Frame-Options
        - âœ… X-Content-Type-Options
        - âœ… No sensitive data in headers

chat:
  auto_reply: true

knowledge_base:
  learnings:
    scope: global
  opt_out: false

  # Project context for AI reviewer
  project_context: |
    ðŸŽ¯ PROJECT: Quantum Kuiper - AI Voice Agent Platform

    ðŸ“‹ TECH STACK:
    - Frontend: Next.js 16 + React 19 + Tailwind CSS 4
    - Backend: Express.js with WebSocket (ws)
    - Database: Supabase (PostgreSQL + pgvector)
    - AI/ML: Transformers.js (local embeddings), OpenAI GPT-4
    - Voice: Deepgram (STT), ElevenLabs (TTS), Simli (avatar)
    - Auth: NextAuth.js 5

    ðŸ—ï¸ ARCHITECTURE:
    - 3-tier RAG system:
      1. Q&A exact match (100% similarity)
      2. Q&A semantic search (>70% threshold)
      3. Vector search on website chunks (fallback)
    - Scale-safe design: Precomputed embeddings (80x faster)
    - Real-time voice streaming with <200ms latency

    ðŸ”’ SECURITY PRIORITIES:
    - SSRF protection (block private IPs)
    - XSS prevention (CSP headers)
    - SQL injection prevention (parameterized queries)
    - Input validation (Zod schemas)
    - Sensitive data redaction (Winston logger)
    - Row Level Security (RLS policies)

    âš¡ PERFORMANCE TARGETS:
    - Q&A matching: <100ms
    - Voice response: <200ms end-to-end
    - Database queries: <1000ms
    - Page load: <2s (FCP)

    ðŸ“¦ KEY FILES:
    - src/lib/validation.ts - Zod schemas for all inputs
    - src/lib/logger.ts - Winston logger with redaction
    - src/middleware.ts - Security headers
    - src/app/api/health/route.ts - Health monitoring
    - backend/voice-server.js - WebSocket voice server

    ðŸ§ª TESTING:
    - Jest for unit tests (70% coverage target)
    - Integration tests for API routes
    - Manual testing guide: TEST-YOUR-SYSTEM.md

    ðŸ’° COST OPTIMIZATION:
    - Local embeddings (Transformers.js) = $0/mo vs OpenAI $150/mo
    - Precomputed embeddings = 80x faster, no runtime cost
    - Vertex AI avoided (14x more expensive than custom)
