# Unique ID for your project
sonar.projectKey=manitejakanuri1_quantum-kuiper

# Your SonarCloud Organization Key
sonar.organization=manitejakanuri1

# Project Name (displayed in SonarCloud)
sonar.projectName=quantum-kuiper

# Source code location (current folder)
sonar.sources=.

# Optional: Exclude test files or config folders if needed
# sonar.exclusions=**/*.test.py,**/node_modules/**
